language: cpp
compiler: 
    - clang
    - gcc
dist: trusty
os:
- linux
script:
    make box
eploy:
  provider: releases
  api_key: "GITHUB OAUTH TOKEN"
  file: "box"
  skip_cleanup: true
  on:
    tags: true
